apiVersion: v1
kind: Service
metadata:
  name: koa2
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: koa2
    tier: backend

